import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, Eye, Pencil, Search, Trash2 } from 'lucide-react'
import { EmptyState, IconButton, StatusBadge } from '../ui'
import { currency, date } from '../../utils/format'

export function SearchInput({ value,onChange,placeholder='Search records...' }) { return <label className="relative block w-full sm:w-64"><span className="sr-only">Search records</span><Search aria-hidden size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className="form-control py-2 pl-9"/></label> }
export function FilterDropdown({ value,onChange,options=[],label='All statuses' }) { return <label className="relative block w-full sm:w-auto"><span className="sr-only">Filter by status</span><select aria-label="Filter by status" value={value} onChange={(e)=>onChange(e.target.value)} className="form-control min-w-40 appearance-none py-2 pr-8"><option value="">{label}</option>{options.map((x)=><option key={x}>{x}</option>)}</select><ChevronDown aria-hidden size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2"/></label> }
export function TableToolbar({ search,setSearch,filter,setFilter,options,dateFilter,setDateFilter,children }) { return <div className="flex flex-col justify-between gap-3 border-b border-slate-200/80 p-3 sm:p-4 xl:flex-row xl:items-center"><div className="flex flex-col gap-2 sm:flex-row"><SearchInput value={search} onChange={setSearch}/>{setFilter&&<FilterDropdown value={filter} onChange={setFilter} options={options}/>}<label className="relative hidden lg:block"><span className="sr-only">Date range</span><CalendarDays size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><select aria-label="Date range" value={dateFilter} onChange={(e)=>setDateFilter(e.target.value)} className="form-control min-w-36 appearance-none py-2 pl-9"><option value="">All dates</option><option value="30">Last 30 days</option><option value="quarter">This quarter</option></select></label></div>{children&&<div className="flex flex-wrap gap-2">{children}</div>}</div> }
export function Pagination({ page,pages,onChange,count }) { if(pages<=1)return <div aria-live="polite" className="border-t border-slate-200 px-4 py-3 text-xs text-slate-500">{count} record{count===1?'':'s'}</div>; const candidates=[1,page-1,page,page+1,pages].filter((x,i,a)=>x>=1&&x<=pages&&a.indexOf(x)===i).sort((a,b)=>a-b); return <div className="flex flex-col items-center justify-between gap-3 border-t border-slate-200 px-4 py-3 text-xs text-slate-500 sm:flex-row"><span aria-live="polite">Page {page} of {pages} · {count} records</span><nav aria-label="Table pagination" className="flex items-center gap-1"><IconButton label="Previous page" className="h-8 w-8 border border-slate-200" disabled={page===1} onClick={()=>onChange(page-1)}><ChevronLeft size={14}/></IconButton>{candidates.map((x,i)=><span className="flex items-center gap-1" key={x}>{i>0&&x-candidates[i-1]>1&&<span aria-hidden className="px-1">...</span>}<button aria-current={page===x?'page':undefined} onClick={()=>onChange(x)} className={`h-8 min-w-8 rounded-md border px-2 font-semibold ${page===x?'border-brand-600 bg-brand-600 text-white':'border-slate-200 bg-white hover:bg-slate-50'}`}>{x}</button></span>)}<IconButton label="Next page" className="h-8 w-8 border border-slate-200" disabled={page===pages} onClick={()=>onChange(page+1)}><ChevronRight size={14}/></IconButton></nav></div> }

function display(value,key) { if(key==='status'||key==='risk')return <StatusBadge status={value}/>; if(['amount','value','price','targetPrice','creditLimit','used','available','overdue'].includes(key))return currency(value); if(['created','registered','due','delivery','dispatch','expected','start','end','expiry','updated','uploaded','submitted'].includes(key)&&value)return date(value); if(key==='image')return <img src={value} className="h-10 w-10 rounded-md border border-slate-200 object-cover" alt=""/>; return value??'—' }
export default function DataTable({ rows,columns,onView,onEdit,onDelete,toolbar,pageSize=5,initialFilter='',emptyTitle='No records found',emptyText='Try changing your search or filters.',caption='Records' }) {
  const [search,setSearch]=useState(''); const [filter,setFilter]=useState(initialFilter); const [dateFilter,setDateFilter]=useState(''); const [sort,setSort]=useState({key:'',direction:'asc'}); const [page,setPage]=useState(1); const hasActions=!!(onView||onEdit||onDelete); const statuses=[...new Set(rows.map((row)=>row.status).filter(Boolean))]
  useEffect(()=>{setFilter(initialFilter);setPage(1)},[initialFilter])
  const filtered=useMemo(()=>rows.filter((row)=>{const textMatch=Object.values(row).some((v)=>String(v).toLowerCase().includes(search.toLowerCase()));const rawDate=['created','registered','due','delivery','dispatch','expected','start','end','expiry','updated','uploaded','submitted'].map((key)=>row[key]).find(Boolean);let dateMatch=true;if(dateFilter&&rawDate){const rowDate=new Date(`${String(rawDate).slice(0,10)}T12:00:00`);dateMatch=dateFilter==='30'?rowDate>=new Date('2026-08-10T00:00:00'):rowDate>=new Date('2026-07-01T00:00:00')}return (!filter||row.status===filter)&&textMatch&&dateMatch}).sort((a,b)=>{if(!sort.key)return 0;return String(a[sort.key]).localeCompare(String(b[sort.key]),undefined,{numeric:true})*(sort.direction==='asc'?1:-1)}),[rows,search,filter,dateFilter,sort]); const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const current=Math.min(page,pages); const shown=filtered.slice((current-1)*pageSize,current*pageSize); const sortBy=(key)=>setSort({key,direction:sort.key===key&&sort.direction==='asc'?'desc':'asc'})
  return <div className="surface-card overflow-hidden"><TableToolbar search={search} setSearch={(v)=>{setSearch(v);setPage(1)}} filter={filter} setFilter={(v)=>{setFilter(v);setPage(1)}} options={statuses} dateFilter={dateFilter} setDateFilter={(v)=>{setDateFilter(v);setPage(1)}}>{toolbar}</TableToolbar><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse"><caption className="sr-only">{caption}</caption><thead className="bg-slate-50/90 text-[11px] uppercase tracking-[.06em] text-slate-500"><tr>{columns.map((col)=><th key={col.key} aria-sort={sort.key===col.key?(sort.direction==='asc'?'ascending':'descending'):'none'} className={`table-cell sticky top-0 z-10 bg-slate-50/95 font-semibold ${col.className||''}`}>{col.sortable===false?col.label:<button className="flex items-center gap-1.5 rounded hover:text-slate-800" onClick={()=>sortBy(col.key)}>{col.label}<ChevronsUpDown aria-hidden size={12}/></button>}</th>)}{hasActions&&<th className="table-cell sticky right-0 top-0 z-20 bg-slate-50/95 text-right font-semibold">Actions</th>}</tr></thead><tbody>{shown.map((row)=><tr key={row.id} className="group transition-colors duration-150 hover:bg-brand-50/35">{columns.map((col)=><td key={col.key} className={`table-cell max-w-[280px] ${col.primary?'font-semibold text-slate-900':''} ${col.className||''}`}><div className="truncate" title={typeof row[col.key]==='string'?row[col.key]:undefined}>{col.render?col.render(row[col.key],row):display(row[col.key],col.key)}</div></td>)}{hasActions&&<td className="table-cell sticky right-0 bg-white text-right transition-colors group-hover:bg-[#f7fbff]"><div className="flex justify-end gap-0.5">{onView&&<IconButton label="View record" className="h-8 w-8" onClick={()=>onView(row)}><Eye size={15}/></IconButton>}{onEdit&&<IconButton label="Edit record" className="h-8 w-8" onClick={()=>onEdit(row)}><Pencil size={15}/></IconButton>}{onDelete&&<IconButton label="Delete record" className="h-8 w-8 text-red-600 hover:bg-red-50 hover:text-red-700" onClick={()=>onDelete(row)}><Trash2 size={15}/></IconButton>}</div></td>}</tr>)}</tbody></table>{!shown.length&&<EmptyState title={emptyTitle} text={emptyText}/>}</div><Pagination page={current} pages={pages} count={filtered.length} onChange={setPage}/></div>
}
