import { useEffect, useId, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BarChart3 } from 'lucide-react'
import { buyerGrowthSeries, conversionSeries, dealPipeline, inventoryByWarehouse, invoiceStatus, orderSeries, revenueSeries } from '../../data/chartData'

const palette=['#1e66a1','#0f766e','#7c3aed','#d97706','#dc2626','#64748b']
const fullCurrency=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})
const compactCurrency=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1})
const count=new Intl.NumberFormat('en-US')
const formats={currency:(value)=>fullCurrency.format(value),compactCurrency:(value)=>compactCurrency.format(value),count:(value)=>count.format(value),percent:(value)=>`${Number(value).toFixed(value%1?1:0)}%`}
const tickStyle={fontSize:11,fill:'#64748b'}

function useMotion() { const [enabled,setEnabled]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches); useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setEnabled(!media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);return enabled }
function EmptyChart() { return <div className="flex h-full flex-col items-center justify-center text-center"><BarChart3 size={24} className="text-slate-300"/><p className="mt-2 text-xs font-semibold text-slate-600">No analytics data available for this period.</p><p className="mt-1 text-[11px] text-slate-400">Choose another reporting period.</p></div> }
function EnterpriseTooltip({active,payload,label}) { if(!active||!payload?.length)return null; return <div className="rounded-lg border border-slate-200 bg-white p-3 shadow-float"><p className="mb-2 text-xs font-semibold text-slate-800">{label}</p>{payload.filter((item)=>item.value!==undefined).map((item)=><div key={item.dataKey} className="flex min-w-36 items-center justify-between gap-4 py-0.5 text-xs"><span className="flex items-center gap-1.5 text-slate-500"><i className="h-2 w-2 rounded-full" style={{background:item.color}}/>{item.name}</span><strong>{formats[item.payload?.formats?.[item.dataKey]||item.format||'count'](item.value)}</strong></div>)}</div> }
function ChartShell({data,children,label}) { if(!data?.length)return <EmptyChart/>; return <div role="img" aria-label={label} className="h-full min-w-0"><ResponsiveContainer width="100%" height="100%" debounce={80}>{children}</ResponsiveContainer></div> }
const grid=<CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb"/>

export function RevenueChart({data=revenueSeries}) { const animate=useMotion();const gradient=useId().replaceAll(':','');return <ChartShell data={data} label="Revenue by month"><AreaChart data={data} margin={{top:8,right:8,left:0,bottom:0}}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1e66a1" stopOpacity=".26"/><stop offset="1" stopColor="#1e66a1" stopOpacity="0"/></linearGradient></defs>{grid}<XAxis dataKey={data[0]?.period?'period':'month'} tick={tickStyle} tickLine={false} axisLine={false}/><YAxis width={52} tick={tickStyle} tickFormatter={formats.compactCurrency} tickLine={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Area isAnimationActive={animate} animationDuration={600} type="monotone" dataKey="revenue" name="Revenue" stroke="#1e66a1" strokeWidth={2} fill={`url(#${gradient})`} activeDot={{r:4}}/></AreaChart></ChartShell> }
export function OrdersChart({data=orderSeries}) { const animate=useMotion();return <ChartShell data={data} label="Purchase and completed orders by month"><BarChart data={data} margin={{top:8,right:8,left:0,bottom:0}}>{grid}<XAxis dataKey="period" tick={tickStyle} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} width={38} tick={tickStyle} tickFormatter={formats.count} tickLine={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Legend wrapperStyle={{fontSize:11}}/><Bar isAnimationActive={animate} dataKey="purchaseOrders" name="Purchase Orders" fill="#1e66a1" radius={[3,3,0,0]}/><Bar isAnimationActive={animate} dataKey="completed" name="Completed" fill="#86b7df" radius={[3,3,0,0]}/></BarChart></ChartShell> }
export function BuyerGrowthChart({data=buyerGrowthSeries}) { const animate=useMotion();return <ChartShell data={data} label="Active and new buyers by month"><LineChart data={data} margin={{top:8,right:8,left:0,bottom:0}}>{grid}<XAxis dataKey="period" tick={tickStyle} tickLine={false} axisLine={false}/><YAxis yAxisId="left" width={38} tick={tickStyle} allowDecimals={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" width={28} tick={tickStyle} allowDecimals={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Legend wrapperStyle={{fontSize:11}}/><Line yAxisId="left" isAnimationActive={animate} type="monotone" dataKey="activeBuyers" name="Active Buyers" stroke="#7c3aed" strokeWidth={2} dot={false}/><Line yAxisId="right" isAnimationActive={animate} type="monotone" dataKey="newBuyers" name="New Buyers" stroke="#0f766e" strokeWidth={2} strokeDasharray="5 4"/></LineChart></ChartShell> }
export function ConversionChart({data=conversionSeries}) { const animate=useMotion();return <ChartShell data={data} label="Quotation conversion percentage by month"><LineChart data={data} margin={{top:8,right:10,left:0,bottom:0}}>{grid}<XAxis dataKey="period" tick={tickStyle} tickLine={false} axisLine={false}/><YAxis domain={[0,100]} width={42} tick={tickStyle} tickFormatter={formats.percent} tickLine={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Line isAnimationActive={animate} type="monotone" dataKey="conversion" name="Conversion" stroke="#7c3aed" strokeWidth={2} dot={false} activeDot={{r:4}}/></LineChart></ChartShell> }
export function PipelineChart({data=dealPipeline,valueKey='count',valueFormat='count'}) { const animate=useMotion();const rows=data.map((item)=>({...item,formats:{[valueKey]:valueFormat}}));return <ChartShell data={rows} label="Deal pipeline by stage"><BarChart data={rows} layout="vertical" margin={{top:4,right:20,left:12,bottom:0}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e5e7eb"/><XAxis type="number" tick={tickStyle} tickFormatter={formats[valueFormat]} axisLine={false}/><YAxis type="category" dataKey="stage" width={90} tick={tickStyle} tickLine={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Bar isAnimationActive={animate} dataKey={valueKey} name={valueKey==='value'?'Pipeline Value':'Deals'} fill="#1e66a1" radius={[0,4,4,0]}>{rows.map((_,index)=><Cell key={index} fill={palette[index%palette.length]}/>)}</Bar></BarChart></ChartShell> }
export function CategoryBarChart({data,dataKey='value',name='Value',format='currency',labelKey='category'}) { const animate=useMotion();const rows=data.map((item)=>({...item,formats:{[dataKey]:format}}));return <ChartShell data={rows} label={`${name} by ${labelKey}`}><BarChart data={rows} layout="vertical" margin={{top:4,right:20,left:12,bottom:0}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e5e7eb"/><XAxis type="number" tick={tickStyle} tickFormatter={formats[format]} axisLine={false}/><YAxis type="category" dataKey={labelKey} width={112} tick={tickStyle} tickLine={false} axisLine={false}/><Tooltip content={<EnterpriseTooltip/>}/><Bar isAnimationActive={animate} dataKey={dataKey} name={name} fill="#1e66a1" radius={[0,4,4,0]}/></BarChart></ChartShell> }
export function StatusDonutChart({data=invoiceStatus,label='Status distribution'}) { const animate=useMotion();return <ChartShell data={data} label={label}><PieChart><Pie isAnimationActive={animate} data={data} dataKey="value" nameKey="name" innerRadius="54%" outerRadius="78%" paddingAngle={3}>{data.map((_,index)=><Cell key={index} fill={palette[index%palette.length]}/>)}</Pie><Tooltip content={<EnterpriseTooltip/>}/><Legend iconType="circle" wrapperStyle={{fontSize:11}}/></PieChart></ChartShell> }
export function InventoryPositionChart({data=inventoryByWarehouse}) { const animate=useMotion();return <ChartShell data={data} label="Available, reserved and allocated stock by warehouse"><BarChart data={data} margin={{top:8,right:8,left:0,bottom:0}}>{grid}<XAxis dataKey="warehouse" tick={tickStyle}/><YAxis tick={tickStyle} tickFormatter={formats.count}/><Tooltip content={<EnterpriseTooltip/>}/><Legend wrapperStyle={{fontSize:11}}/><Bar isAnimationActive={animate} stackId="stock" dataKey="available" name="Available" fill="#1e66a1"/><Bar isAnimationActive={animate} stackId="stock" dataKey="reserved" name="Reserved" fill="#d97706"/><Bar isAnimationActive={animate} stackId="stock" dataKey="allocated" name="Allocated" fill="#7c3aed"/></BarChart></ChartShell> }

export const GrowthChart=BuyerGrowthChart
export const PurchaseChart=OrdersChart
export function RepPerformanceChart({data=[]}) { return <CategoryBarChart data={data} labelKey="name" name="Booked PO Value" format="currency"/> }
