import { useEffect, useState } from 'react'
import { ChevronLeft, ChevronRight, Circle, PanelLeftClose, PanelLeftOpen, X } from 'lucide-react'
import { Link, useLocation } from 'react-router-dom'
import BrandLogo from '../common/BrandLogo'
import { Avatar, IconButton } from '../ui'

const matchesPath = (target, location) => {
  const [pathname, query=''] = target.split('?')
  if (location.pathname !== pathname && !location.pathname.startsWith(`${pathname}/`)) return false
  if (!query) return location.pathname !== pathname || !location.search
  return new URLSearchParams(location.search).toString() === new URLSearchParams(query).toString()
}

export default function MainSidebar({ navigation, collapsed, mobileOpen, onClose, onCollapse, name, role }) {
  const location=useLocation(); const [expanded,setExpanded]=useState({}); const showLabels=mobileOpen||!collapsed
  useEffect(()=>{ navigation.forEach((section)=>section.items.forEach((item)=>{if(item.children?.some((child)=>location.pathname===child.path.split('?')[0]||location.pathname.startsWith(`${child.path.split('?')[0]}/`)))setExpanded((x)=>({...x,[item.label]:true}))})) },[location.pathname,navigation])
  useEffect(()=>{if(!mobileOpen)return; const close=(e)=>e.key==='Escape'&&onClose(); const old=document.body.style.overflow; document.body.style.overflow='hidden'; document.addEventListener('keydown',close); return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',close)}},[mobileOpen,onClose])
  const toggleGroup=(label)=>{if(collapsed&&!mobileOpen){onCollapse();setExpanded((x)=>({...x,[label]:true}));return}setExpanded((x)=>({...x,[label]:!x[label]}))}
  return <aside aria-label="Primary navigation" className={`app-sidebar fixed inset-y-0 left-0 z-50 flex flex-col overflow-hidden bg-sidebar text-slate-300 shadow-xl transition-[width,transform] duration-200 lg:translate-x-0 ${collapsed?'lg:w-[76px]':'lg:w-[264px]'} ${mobileOpen?'w-[264px] translate-x-0':'w-[264px] -translate-x-full'}`}>
    <div className={`flex h-16 shrink-0 items-center border-b border-white/[.08] bg-[#121b24] px-5 ${showLabels?'':'justify-center'}`}><BrandLogo variant="sidebar" />{showLabels&&<span className="ml-3 min-w-0"><strong className="block whitespace-nowrap text-[13px] tracking-wide text-white">PhsarDom</strong><small className="block text-[11px] text-slate-500">B2B Wholesale</small></span>}<IconButton label="Close navigation" onClick={onClose} className="ml-auto text-slate-300 hover:bg-white/10 hover:text-white lg:hidden"><X size={19}/></IconButton></div>
    <div className={`flex min-h-[72px] items-center border-b border-white/[.07] px-4 ${showLabels?'gap-3':'justify-center'}`}><Avatar name={name}/>{showLabels&&<span className="min-w-0"><strong className="block truncate text-[13px] font-semibold text-white">{name}</strong><small className="mt-0.5 flex items-center gap-1.5 truncate text-[11px] text-slate-400"><Circle size={7} fill="#34d399" className="text-emerald-400"/>{role}</small></span>}</div>
    <nav className="flex-1 overflow-y-auto overflow-x-hidden px-2 py-3 [scrollbar-color:#334155_transparent] [scrollbar-width:thin]">{navigation.map((section)=><div key={section.label} className="mb-3">{showLabels?<p className="px-3 pb-1.5 pt-2 text-[10px] font-bold tracking-[.14em] text-slate-500">{section.label}</p>:<div className="mx-auto my-2 h-px w-7 bg-white/10"/>}{section.items.map((item)=>{const Icon=item.icon;const parentActive=item.children?.some((child)=>location.pathname===child.path.split('?')[0]||location.pathname.startsWith(`${child.path.split('?')[0]}/`));const directActive=item.path&&(location.pathname===item.path||location.pathname.startsWith(`${item.path}/`));return <div key={item.label} className="relative">{item.children?<button title={!showLabels?item.label:undefined} aria-expanded={!!expanded[item.label]} onClick={()=>toggleGroup(item.label)} className={`group flex min-h-10 w-full items-center rounded-md px-3 text-left transition-colors ${parentActive?'bg-white/[.08] text-white':'hover:bg-white/[.055] hover:text-white'} ${showLabels?'':'justify-center'}`}><Icon size={18} className="shrink-0"/>{showLabels&&<><span className="ml-3 flex-1 whitespace-nowrap text-[13px]">{item.label}</span><ChevronRight size={14} className={`transition-transform duration-200 ${expanded[item.label]?'rotate-90':''}`}/></>}</button>:<Link title={!showLabels?item.label:undefined} to={item.path} onClick={onClose} className={`group flex min-h-10 items-center rounded-md px-3 transition-colors ${directActive?'bg-brand-600 text-white shadow-sm':'hover:bg-white/[.055] hover:text-white'} ${showLabels?'':'justify-center'}`}><Icon size={18} className="shrink-0"/>{showLabels&&<span className="ml-3 whitespace-nowrap text-[13px]">{item.label}</span>}</Link>}{item.children&&showLabels&&<div className={`grid transition-[grid-template-rows,opacity] duration-200 ${expanded[item.label]?'grid-rows-[1fr] opacity-100':'grid-rows-[0fr] opacity-0'}`}><div className="overflow-hidden"><div className="relative ml-5 border-l border-white/10 py-1 pl-3">{item.children.map((child)=>{const active=matchesPath(child.path,location);return <Link key={child.label} to={child.path} onClick={onClose} className={`relative flex min-h-9 items-center rounded px-3 text-xs transition-colors before:absolute before:-left-3 before:top-1/2 before:h-px before:w-3 before:bg-white/10 ${active?'bg-white/[.07] font-semibold text-cyan-300':'text-slate-400 hover:bg-white/[.04] hover:text-white'}`}>{child.label}</Link>})}</div></div></div>}</div>})}</div>)}</nav>
    <button title={collapsed?'Expand sidebar':'Collapse sidebar'} onClick={onCollapse} className="hidden min-h-12 items-center justify-center gap-2 border-t border-white/[.08] text-xs text-slate-400 transition hover:bg-white/[.04] hover:text-white lg:flex">{collapsed?<PanelLeftOpen size={18}/>:<><PanelLeftClose size={18}/><span>Collapse sidebar</span></>}</button>
  </aside>
}
