import { useEffect, useRef, useState } from 'react'
import { Bell, Expand, LogOut, Mail, Menu, Plus, Search, Settings, User } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Avatar, IconButton } from '../ui'

const roleRoot={'Verified Buyer':'buyer','Account Executive':'sales','Sales Manager':'manager','Super Admin':'admin'}
const quickRoutes={buyer:['New RFQ','/buyer/rfqs/new'],sales:['New Quote','/sales/quotations/new'],manager:['Review Approvals','/manager/approvals'],admin:['Add Product','/admin/products/new']}
const searchItems={buyer:[['Products','products'],['RFQs','rfqs'],['Quotations','quotations'],['Purchase Orders','purchase-orders'],['Invoices','invoices'],['Shipments','shipments']],sales:[['Buyers','buyers'],['RFQs','rfqs'],['Quotations','quotations'],['Purchase Orders','purchase-orders'],['Contracts','contracts']],manager:[['Approvals','approvals'],['RFQs','rfqs'],['Quotations','quotations'],['Purchase Orders','purchase-orders'],['Contracts','contracts']],admin:[['Products','products'],['Buyers','buyers'],['RFQs','rfqs'],['Purchase Orders','purchase-orders'],['Invoices','invoices'],['Shipments','shipments']]}

export default function TopNavbar({ onToggle,role,name,title }) {
  const [open,setOpen]=useState(null); const [query,setQuery]=useState(''); const [counts,setCounts]=useState({messages:3,notifications:7}); const navigate=useNavigate(); const location=useLocation(); const root=roleRoot[role]; const wrapRef=useRef(null); const quick=quickRoutes[root]
  useEffect(()=>setOpen(null),[location.pathname,location.search])
  useEffect(()=>{const outside=(e)=>!wrapRef.current?.contains(e.target)&&setOpen(null);const key=(e)=>e.key==='Escape'&&setOpen(null);document.addEventListener('mousedown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',key)}},[])
  const fullscreen=async()=>{try{if(!document.fullscreenEnabled)return;if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{return}}
  const goSearch=(item)=>{navigate(`/${root}/${item[1]}`);setQuery('');setOpen(null)}
  const dropdown=(key,Icon,content)=> <div className="relative"><IconButton label={key==='messages'?'Messages':'Notifications'} aria-expanded={open===key} onClick={()=>setOpen(open===key?null:key)} className="relative"><Icon size={18}/>{counts[key]>0&&<span className="absolute right-1 top-1 min-w-4 rounded-full bg-red-600 px-1 text-center text-[9px] font-bold leading-4 text-white">{counts[key]}</span>}</IconButton>{open===key&&<div className="popover-enter fixed right-2 top-[60px] w-80 max-w-[calc(100vw-1rem)] overflow-hidden rounded-lg border border-slate-200 bg-white shadow-float md:absolute md:right-0 md:top-11"><div className="flex items-center justify-between border-b px-4 py-3"><strong className="text-xs uppercase tracking-wide text-slate-700">{key}</strong><button onClick={()=>setCounts({...counts,[key]:0})} className="text-xs font-semibold text-brand-700">Mark all read</button></div>{content}<button onClick={()=>navigate(key==='messages'?`/${root}/rfqs/1`:`/${root}/notifications`)} className="w-full border-t px-4 py-3 text-xs font-semibold text-brand-700 hover:bg-slate-50">{key==='messages'?'Open related RFQ':'View all notifications'}</button></div>}</div>
  return <header ref={wrapRef} className="app-navbar sticky top-0 z-30 flex h-16 items-center border-b border-slate-200/90 bg-white/95 px-3 backdrop-blur sm:px-5">
    <IconButton label="Toggle navigation" onClick={onToggle}><Menu size={20}/></IconButton>
    <div className="ml-2 hidden min-w-0 sm:block"><span className="block truncate text-[13px] font-semibold text-slate-800">{title}</span><small className="text-[11px] text-slate-500">PhsarDom · {role} workspace</small></div>
    <div className="relative ml-auto hidden lg:block"><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input aria-label="Global search" value={query} onFocus={()=>setOpen('search')} onChange={(e)=>{setQuery(e.target.value);setOpen('search')}} className="h-9 w-64 rounded-md border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none transition focus:border-brand-500 focus:bg-white focus:ring-2 focus:ring-brand-500/10" placeholder="Search modules..."/>{open==='search'&&query&&<div className="popover-enter absolute right-0 top-11 w-64 rounded-lg border bg-white p-1.5 shadow-float">{searchItems[root].filter(([label])=>label.toLowerCase().includes(query.toLowerCase())).map((item)=><button key={item[0]} onClick={()=>goSearch(item)} className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-xs hover:bg-slate-50"><Search size={13}/>{item[0]}</button>)}</div>}</div>
    <div className="ml-auto flex items-center gap-0.5 lg:ml-3"><button onClick={()=>navigate(quick[1])} className="btn-primary mr-1 hidden md:inline-flex"><Plus size={14}/>{quick[0]}</button><IconButton label="Toggle fullscreen" onClick={fullscreen} className="hidden md:inline-flex"><Expand size={17}/></IconButton>{dropdown('messages',Mail,<div className="p-3"><p className="rounded-md bg-slate-50 p-3 text-xs text-slate-600"><strong className="block text-slate-800">Daniel Brooks</strong>Pricing review requested for QT-2026-0832.</p></div>)}{dropdown('notifications',Bell,<div className="p-3"><p className="rounded-md bg-blue-50 p-3 text-xs text-blue-800">RFQ-2026-1048 requires your attention.</p></div>)}<div className="relative"><button aria-expanded={open==='profile'} onClick={()=>setOpen(open==='profile'?null:'profile')} className="ml-1 flex min-h-10 items-center gap-2 rounded-md px-1.5 transition hover:bg-slate-100"><Avatar name={name} size="sm"/><span className="hidden text-left xl:block"><strong className="block text-xs text-slate-800">{name}</strong><small className="text-[10px] text-slate-500">{role}</small></span></button>{open==='profile'&&<div className="popover-enter absolute right-0 top-12 w-52 overflow-hidden rounded-lg border bg-white p-1.5 shadow-float"><div className="mb-1 border-b px-3 py-2"><strong className="block text-xs">{name}</strong><small>{role}</small></div><button onClick={()=>navigate(`/${root}/profile`)} className="flex w-full items-center gap-2 rounded px-3 py-2 text-xs hover:bg-slate-50"><User size={15}/>Profile</button><button onClick={()=>navigate(root==='admin'?'/admin/settings':`/${root}/profile`)} className="flex w-full items-center gap-2 rounded px-3 py-2 text-xs hover:bg-slate-50"><Settings size={15}/>Account Settings</button><button onClick={()=>navigate('/login')} className="flex w-full items-center gap-2 rounded px-3 py-2 text-xs text-red-700 hover:bg-red-50"><LogOut size={15}/>Sign Out</button></div>}</div></div>
  </header>
}
