import { useEffect, useState } from 'react'
import { Save } from 'lucide-react'
import { Button, DateInput, FileUpload, SelectInput, Textarea, TextInput } from '../ui'

const valuesFrom = (schema, initial) => Object.fromEntries(schema.sections.flatMap((section) => section.fields).filter((field) => !(initial?.id && field.createOnly)).map((field) => [field.name, initial?.[field.name] ?? field.defaultValue ?? (field.type === 'number' ? '' : '')]))
const normalizeOptions = (options = []) => options.map((item) => typeof item === 'string' ? { value: item, label: item } : item)

export default function SchemaForm({ schema, initial = {}, onSubmit, onCancel }) {
  const [values,setValues]=useState(()=>valuesFrom(schema,initial)); const [errors,setErrors]=useState({}); const [submitting,setSubmitting]=useState(false)
  useEffect(()=>{setValues(valuesFrom(schema,initial));setErrors({});setSubmitting(false)},[schema,initial?.id])
  const change=(name)=>(event)=>{setValues((current)=>({...current,[name]:event.target.value}));setErrors((current)=>({...current,[name]:''}))}
  const submit=async(event)=>{event.preventDefault();if(submitting)return;const next={};schema.sections.flatMap((section)=>section.fields).filter((field)=>!(initial?.id&&field.createOnly)).forEach((field)=>{const value=values[field.name];if(field.required&&(value===undefined||value===null||String(value).trim()===''))next[field.name]=`${field.label} is required.`;if(field.type==='number'&&value!==''&&field.min!==undefined&&Number(value)<field.min)next[field.name]=`${field.label} must be at least ${field.min}.`;if(field.type==='number'&&value!==''&&field.max!==undefined&&Number(value)>field.max)next[field.name]=`${field.label} cannot exceed ${field.max}.`});if(Object.keys(next).length){setErrors(next);requestAnimationFrame(()=>document.querySelector('[aria-invalid="true"]')?.focus());return}setSubmitting(true);await new Promise((resolve)=>setTimeout(resolve,450));const payload=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,value!==''&&!Number.isNaN(Number(value))&&schema.sections.flatMap((section)=>section.fields).find((field)=>field.name===key)?.type==='number'?Number(value):value]));await onSubmit({...initial,...payload});setSubmitting(false)}
  return <form onSubmit={submit} className="space-y-5">{schema.sections.map((section)=><fieldset key={section.title} className="rounded-lg border border-slate-200 bg-slate-50/40 p-4"><legend className="px-1 text-xs font-semibold uppercase tracking-wide text-slate-600">{section.title}</legend><div className="mt-2 grid gap-4 sm:grid-cols-2">{section.fields.filter((field)=>!(initial?.id&&field.createOnly)).map((field)=>{const common={key:field.name,name:field.name,label:field.label,required:field.required,error:errors[field.name],hint:field.hint,value:values[field.name],onChange:change(field.name)};if(field.type==='select')return <SelectInput {...common}>{normalizeOptions(field.options).map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</SelectInput>;if(field.type==='textarea')return <div key={field.name} className="sm:col-span-2"><Textarea {...common}/></div>;if(field.type==='date')return <DateInput {...common} min={field.min}/>;if(field.type==='file')return <div key={field.name} className="sm:col-span-2"><FileUpload name={field.name} label={field.label} required={field.required}/></div>;return <TextInput {...common} type={field.type} min={field.min} max={field.max} step={field.step} minLength={field.minLength} placeholder={field.placeholder}/>})}</div></fieldset>)}<div className="sticky bottom-0 -mx-5 -mb-5 flex flex-wrap justify-end gap-2 border-t border-slate-200 bg-white/95 px-5 py-3 backdrop-blur"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" loading={submitting}><Save size={14}/>{initial?.id?'Save Changes':`Create ${schema.label}`}</Button></div></form>
}
